import SwiftUI

// NeoTorrentSession is generated by UniFFI. The underlying Rust handle is
// `Send + Sync`, so it's safe to share across actor boundaries. Promise that
// to Swift here so we can pass it freely between MainActor and Tasks.
extension NeoTorrentSession: @unchecked Sendable {}

@main
struct NeoTorrentApp: App {
    @State private var sessionHolder = SessionHolder()
    @State private var prefs = Preferences()

    var body: some Scene {
        Window("NeoTorrent", id: "main") {
            ContentView()
                .environment(sessionHolder)
                .environment(prefs)
                .frame(minWidth: 560, minHeight: 200)
                .task { await start() }
                .onOpenURL { url in
                    sessionHolder.handleOpenURL(url)
                }
        }
        .windowStyle(.titleBar)
        .windowToolbarStyle(.unified)
        .windowResizability(.contentSize)

        Settings {
            SettingsView()
                .environment(prefs)
        }
    }

    private func start() async {
        await sessionHolder.start(downloadDir: prefs.downloadDir)
        if let session = sessionHolder.session {
            prefs.attach(session, sessionDir: prefs.downloadDir)
        }
    }
}

struct PendingTorrent: Identifiable {
    let id = UUID()
    var name: String
}

@MainActor
@Observable
final class SessionHolder {
    var session: NeoTorrentSession?
    var startupError: String?
    var pendingAdds: [PendingTorrent] = []
    private var preStartQueue: [String] = []

    func start(downloadDir: String) async {
        guard session == nil else { return }
        let stateDir = (NSHomeDirectory() as NSString)
            .appendingPathComponent("Library/Application Support/neotorrent")
        try? FileManager.default.createDirectory(atPath: downloadDir, withIntermediateDirectories: true)
        try? FileManager.default.createDirectory(atPath: stateDir, withIntermediateDirectories: true)
        do {
            let s = try await NeoTorrentSession(downloadDir: downloadDir, stateDir: stateDir)
            session = s
            let queued = preStartQueue
            preStartQueue.removeAll()
            for uri in queued {
                _ = try? await add(uri: uri)
            }
        } catch {
            startupError = "Failed to start session: \(error.localizedDescription)"
        }
    }

    @discardableResult
    func add(uri: String) async throws -> UInt64? {
        guard let session else {
            preStartQueue.append(uri)
            return nil
        }
        let entry = PendingTorrent(name: displayName(for: uri))
        pendingAdds.append(entry)
        defer { pendingAdds.removeAll { $0.id == entry.id } }
        return try await session.addMagnet(uri: uri)
    }

    func handleOpenURL(_ url: URL) {
        let uri: String
        if url.scheme == "magnet" {
            uri = url.absoluteString
        } else if url.isFileURL && url.pathExtension.lowercased() == "torrent" {
            uri = url.path
        } else {
            return
        }
        Task { _ = try? await add(uri: uri) }
    }

    private func displayName(for uri: String) -> String {
        if uri.hasPrefix("magnet:") {
            if let parsed = try? parseMagnet(uri: uri) {
                if let n = parsed.displayName, !n.isEmpty { return n }
                return "Magnet (\(parsed.infoHash.prefix(8))…)"
            }
            return "Magnet"
        }
        let url = URL(fileURLWithPath: uri)
        return url.deletingPathExtension().lastPathComponent
    }
}
