import SwiftUI
import AppKit

// NeoTorrentSession is generated by UniFFI. The underlying Rust handle is
// `Send + Sync`, so it's safe to share across actor boundaries. Promise that
// to Swift here so we can pass it freely between MainActor and Tasks.
extension NeoTorrentSession: @unchecked Sendable {}

final class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        false
    }

    func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows flag: Bool) -> Bool {
        if !flag {
            for window in sender.windows where window.canBecomeMain {
                window.makeKeyAndOrderFront(nil)
            }
        }
        return true
    }
}

@main
struct NeoTorrentApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) private var appDelegate
    @State private var sessionHolder = SessionHolder()
    @State private var prefs = Preferences()

    var body: some Scene {
        Window("NeoTorrent", id: "main") {
            ContentView()
                .environment(sessionHolder)
                .environment(prefs)
                .frame(minWidth: 640, idealWidth: 820, minHeight: 480, idealHeight: 640)
                .task { await start() }
                .onOpenURL { url in
                    sessionHolder.handleOpenURL(url)
                }
        }
        .windowStyle(.titleBar)
        .windowToolbarStyle(.unified)

        Settings {
            SettingsView()
                .environment(prefs)
        }
        .windowResizability(.contentSize)
    }

    private func start() async {
        await sessionHolder.start(downloadDir: prefs.downloadDir)
        if let session = sessionHolder.session {
            prefs.attach(session, sessionDir: prefs.downloadDir)
        }
    }
}

struct PendingTorrent: Identifiable {
    let id = UUID()
    var name: String
    var torrentID: UInt64?
}

enum AddTorrentError: LocalizedError {
    case alreadyAdded(name: String)

    var errorDescription: String? {
        switch self {
        case .alreadyAdded(let name): return "“\(name)” is already in your list"
        }
    }
}

@MainActor
@Observable
final class SessionHolder {
    var session: NeoTorrentSession?
    var startupError: String?
    var addError: String?
    var pendingAdds: [PendingTorrent] = []
    private var preStartQueue: [String] = []
    private var cancelledPending: Set<UUID> = []

    func start(downloadDir: String) async {
        guard session == nil else { return }
        let stateDir = (NSHomeDirectory() as NSString)
            .appendingPathComponent("Library/Application Support/neotorrent")
        try? FileManager.default.createDirectory(atPath: downloadDir, withIntermediateDirectories: true)
        try? FileManager.default.createDirectory(atPath: stateDir, withIntermediateDirectories: true)
        do {
            let s = try await NeoTorrentSession(downloadDir: downloadDir, stateDir: stateDir)
            session = s
            let queued = preStartQueue
            preStartQueue.removeAll()
            for uri in queued {
                _ = try? await add(uri: uri)
            }
        } catch {
            startupError = "Failed to start session: \(error.localizedDescription)"
        }
    }

    @discardableResult
    func add(uri: String) async throws -> UInt64? {
        guard let session else {
            preStartQueue.append(uri)
            return nil
        }
        let existing = session.list()
        if uri.hasPrefix("magnet:"), let parsed = try? parseMagnet(uri: uri),
           let match = existing.first(where: { $0.infoHash.caseInsensitiveCompare(parsed.infoHash) == .orderedSame })
        {
            throw AddTorrentError.alreadyAdded(name: match.name ?? parsed.displayName ?? "Magnet")
        }
        let existingIDs = Set(existing.map { $0.id })
        let entry = PendingTorrent(name: displayName(for: uri))
        pendingAdds.append(entry)
        do {
            let id = try await session.addMagnet(uri: uri)
            if cancelledPending.contains(entry.id) {
                cancelledPending.remove(entry.id)
                try? await session.remove(id: id, deleteFiles: false)
                return id
            }
            if existingIDs.contains(id) {
                pendingAdds.removeAll { $0.id == entry.id }
                let existingName = session.list().first(where: { $0.id == id })?.name ?? entry.name
                throw AddTorrentError.alreadyAdded(name: existingName)
            }
            if let i = pendingAdds.firstIndex(where: { $0.id == entry.id }) {
                pendingAdds[i].torrentID = id
            }
            return id
        } catch {
            pendingAdds.removeAll { $0.id == entry.id }
            cancelledPending.remove(entry.id)
            throw error
        }
    }

    func cancelPending(_ pendingID: UUID) {
        let entry = pendingAdds.first { $0.id == pendingID }
        pendingAdds.removeAll { $0.id == pendingID }
        if let torrentID = entry?.torrentID, let session {
            Task { try? await session.remove(id: torrentID, deleteFiles: false) }
        } else {
            cancelledPending.insert(pendingID)
        }
    }

    func reconcilePending(against torrentIDs: Set<UInt64>) {
        pendingAdds.removeAll { p in
            guard let tid = p.torrentID else { return false }
            return torrentIDs.contains(tid)
        }
    }

    func handleOpenURL(_ url: URL) {
        let uri: String
        if url.scheme == "magnet" {
            uri = url.absoluteString
        } else if url.isFileURL && url.pathExtension.lowercased() == "torrent" {
            uri = url.path
        } else {
            return
        }
        Task {
            do { _ = try await add(uri: uri) }
            catch { addError = errorMessage(error) }
        }
    }

    private func errorMessage(_ error: Error) -> String {
        if let e = error as? AddTorrentError {
            return e.errorDescription ?? String(describing: e)
        }
        return error.localizedDescription
    }

    private func displayName(for uri: String) -> String {
        if uri.hasPrefix("magnet:") {
            if let parsed = try? parseMagnet(uri: uri) {
                if let n = parsed.displayName, !n.isEmpty { return n }
                return "Magnet (\(parsed.infoHash.prefix(8))…)"
            }
            return "Magnet"
        }
        let url = URL(fileURLWithPath: uri)
        return url.deletingPathExtension().lastPathComponent
    }
}
